kind: pipeline
type: docker
name: backend

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      repo: 100.98.49.87:5000/forum-ws
      registry: 100.98.49.87:5000
      insecure: true

trigger:
  branch:
    - main
