kind: pipeline
type: docker
name: backend

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      repo: 172.22.154.209:5000/forum-backend-app
      registry: 172.22.154.209:5000
      insecure: true

trigger:
  branch:
    - main
