kind: pipeline
type: docker
name: backend

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      repo: 192.168.0.212/5000/forum-ws-app
      registry: 192.168.0.212:5000
      insecure: true

trigger:
  branch:
    - main
